### ISSUE TITLE
Add tagging to the mrversion functionality

### ISSUE THREAD

**Issue by area42** [PenCue/mrversion#12]
# PenCue Feature Request

**Is your feature request related to a problem? Please describe.**
Have an optional tagging and pushing of the tags as last step. So the extra step in the workflow is not needed. 

**Describe the solution you'd like**
action switch:
```yml
with:
          stable-branch: master
          int-branch: int
          dev-branch: dev
          stable-tag: null
          int-tag: rc
          dev-tag: unstable
          version-prefix: v
          tag: full,major,minor
```
no -> no tags
all -> complete set vM.m.p.tag, vM.m.tag and vM.tag
full  -> vM.m.p.tag
major -> vM.tag
minor -> vM.m.tag 
note that major and minor without full makes little sense unless you tag full in some otherway

mrversion will create local tag, delete origin tag, push tag. (delete will fail if tag does not exist). 

**Additional context**
cleaner less errorprone: each tag is 3 steps of which 1 is ok to fail. actions don't like failing steps so needs to be handled.
